# Generated by Django 4.2.3 on 2023-07-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_gender_alter_profile_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image2',
            field=models.ImageField(default='default2.jpg', upload_to='profile_pics'),
        ),
    ]
