# Generated by Django 4.2.3 on 2023-07-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image2',
        ),
    ]
