# Generated by Django 4.2.3 on 2023-07-18 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='from_friend',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_friends', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='to_friend',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='users.profile'),
        ),
    ]
