# Generated by Django 4.2.3 on 2023-07-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_friendship_from_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='length_in_months',
        ),
    ]
